* #1: Moved the code from the virtual-schemas repository.
exasol/teradata-virtual-schema pull request #2
Opened 2020-11-19 10:49 UTC by AnastasiiaSergienko

2020-11-19 12:16 UTC, chiaradiamarcelo requested changes
Looks good, left some comments.

2020-11-19 12:16 UTC, chiaradiamarcelo commented on src/main/java/com/exasol/adapter/dialects/AbstractSqlDialectFactory.java
> +                "META-INF/maven/com.exasol/virtual-schema-jdbc-adapter/pom.properties");
```suggestion
                "META-INF/maven/com.exasol/teradata-virtual-schema/pom.properties");
```

2020-11-19 12:16 UTC, chiaradiamarcelo commented on src/main/java/com/exasol/adapter/dialects/teradata/TeradataMetadataReader.java
> +     * Create a new instance of a {@link TeradataMetadataReader}.
```suggestion
     * Creates a new instance of a {@link TeradataMetadataReader}.
```

2020-11-19 12:16 UTC, chiaradiamarcelo commented on src/main/java/com/exasol/adapter/dialects/teradata/TeradataColumnMetadataReader.java
> +     * Create a new instance of the {@link TeradataColumnMetadataReader}.
```suggestion
     * Creates a new instance of the {@link TeradataColumnMetadataReader}.
```

2020-11-19 12:16 UTC, chiaradiamarcelo commented on src/main/java/com/exasol/adapter/dialects/teradata/TeradataSqlDialect.java
> +     * Create a new instance of the {@link TeradataSqlDialect}.
```suggestion
     * Creates a new instance of the {@link TeradataSqlDialect}.
```

2020-11-19 12:16 UTC, chiaradiamarcelo commented on src/main/java/com/exasol/adapter/dialects/teradata/TeradataSqlGenerationVisitor.java
> +     * Create a new instance of the {@link TeradataSqlGenerationVisitor}.
```suggestion
     * Creates a new instance of the {@link TeradataSqlGenerationVisitor}.
```

2020-11-19 12:16 UTC, chiaradiamarcelo commented on src/main/resources/META-INF/services/com.exasol.adapter.AdapterFactory
> +com.exasol.adapter.jdbc.JdbcAdapterFactory
this file is not necessary as it's provided by the `virtual-schema-common-jdbc` jar in the bundle

2020-11-19 12:16 UTC, chiaradiamarcelo commented on src/test/java/com/exasol/adapter/dialects/teradata/TeradataDialectFactoryTest.java
> +public class TeradataDialectFactoryTest {
```suggestion
class TeradataDialectFactoryTest {
```

2020-11-19 12:16 UTC, chiaradiamarcelo commented on src/test/java/com/exasol/adapter/dialects/teradata/TeradataSqlDialectTest.java
> +    private SqlDialect dialect;
```suggestion
    private TeradataSqlDialect dialect;
```

2020-11-19 12:16 UTC, chiaradiamarcelo commented on src/test/java/com/exasol/adapter/dialects/teradata/TeradataSqlDialectTest.java
> +                instanceOf(TeradataMetadataReader.class));
```suggestion
        assertThat(this.dialect.createRemoteMetadataReader(), instanceOf(TeradataMetadataReader.class));
```

2020-11-19 12:16 UTC, chiaradiamarcelo commented on src/test/java/com/exasol/reflect/ReflectionException.java
> +public final class ReflectionException extends RuntimeException {
this class is not needed

2020-11-19 12:16 UTC, chiaradiamarcelo commented on src/test/java/com/exasol/reflect/ReflectionUtils.java
> +public final class ReflectionUtils {
this class is not necessary

2020-11-19 12:16 UTC, chiaradiamarcelo commented on pom.xml
> +                        <id>prepare-agent-integration</id>
there are not integration test.

I suggest to remove this and add it when the integration test is implemented.

2020-11-19 12:16 UTC, chiaradiamarcelo commented on pom.xml
> +                        <id>report-integration</id>
same comment as above

2020-11-19 12:16 UTC, chiaradiamarcelo commented on pom.xml
> +        <org.testcontainers.version>1.15.0</org.testcontainers.version>
this is not necessary for now

2020-11-19 12:21 UTC, AnastasiiaSergienko commented on src/main/java/com/exasol/adapter/dialects/teradata/TeradataMetadataReader.java
> +     * Create a new instance of a {@link TeradataMetadataReader}.
I think we usually write "Create"

2020-11-19 12:23 UTC, AnastasiiaSergienko commented on src/main/java/com/exasol/adapter/dialects/AbstractSqlDialectFactory.java
> +public abstract class AbstractSqlDialectFactory implements SqlDialectFactory {
I thought maybe we move it to some common place later because we use it in all dialects

2020-11-19 12:24 UTC, AnastasiiaSergienko commented on src/main/java/com/exasol/adapter/dialects/AbstractSqlDialectFactory.java
> +public abstract class AbstractSqlDialectFactory implements SqlDialectFactory {
Ah, the package name is different and we can't do it.  I see now

2020-11-19 12:31 UTC, chiaradiamarcelo commented on src/main/java/com/exasol/adapter/dialects/teradata/TeradataMetadataReader.java
> +     * Create a new instance of a {@link TeradataMetadataReader}.
As I was saying to Jakob, the purpose of a javadoc in a method is to reply to the "what does this method do?" question, which is in present simple. It's also the standard way across all the code in the open JDK.

Personally I prefer to be consistent with the Java way and use the standard, but if you think different, feel free to apply the suggestion or not.

2020-11-19 12:34 UTC, AnastasiiaSergienko commented on src/main/java/com/exasol/adapter/dialects/teradata/TeradataMetadataReader.java
> +     * Create a new instance of a {@link TeradataMetadataReader}.
I think we can discuss it and change later across all code or it will be inconsistent

2020-11-19 12:38 UTC, chiaradiamarcelo commented on src/main/java/com/exasol/adapter/dialects/teradata/TeradataMetadataReader.java
> +     * Create a new instance of a {@link TeradataMetadataReader}.
I agree, but given that is is now a "new" repository, you can just take the opportunity to do it here, and you'll be consistent

2020-11-19 12:39 UTC, chiaradiamarcelo commented on src/main/java/com/exasol/adapter/dialects/teradata/TeradataMetadataReader.java
> +     * Create a new instance of a {@link TeradataMetadataReader}.
@redcatbear what do you think about it?

2020-11-19 13:05 UTC, redcatbear commented on src/main/java/com/exasol/adapter/dialects/teradata/TeradataMetadataReader.java
> +     * Create a new instance of a {@link TeradataMetadataReader}.
Unless you want to change all existing comments in all repositories, please keep it uniform.

2020-11-19 13:07 UTC, redcatbear commented on src/main/java/com/exasol/adapter/dialects/teradata/TeradataMetadataReader.java
> +     * Create a new instance of a {@link TeradataMetadataReader}.
The style you suggest is used in the Java standard library, I'll give you that.

2020-11-19 13:33 UTC, chiaradiamarcelo commented on src/main/java/com/exasol/adapter/dialects/teradata/TeradataMetadataReader.java
> +     * Create a new instance of a {@link TeradataMetadataReader}.
If it's really ok, sure, I can change them in all the repo. They are small enough so it shouldn't take long

2020-11-19 14:44 UTC, chiaradiamarcelo approved these changes

2020-11-19 14:47 UTC, merged

2020-11-20 06:15 UTC, redcatbear commented on src/main/java/com/exasol/adapter/dialects/teradata/TeradataMetadataReader.java
> +     * Create a new instance of a {@link TeradataMetadataReader}.
OK. I will take you by your word. :-)

Good thing for you is that this change does not make a release necessary. That's pure refactoring and has no customer-visible impact, so we can just release it with the next regular release of each project.

2020-11-20 06:16 UTC, redcatbear commented on src/main/java/com/exasol/adapter/dialects/teradata/TeradataMetadataReader.java
> +     * Create a new instance of a {@link TeradataMetadataReader}.
That's a whole lot of comments you are going to rake. On the upside, while you are at it, you can also check whether each comment makes sense.